inline "function check_arity(operator,length,arity)"
inline "{"
inline " return"
inline " if(operator===\"same\")"
inline " {"
inline "  if(length===arity)"
inline "   return"
inline " }"
inline ""
inline " if(operator===\"gte\")"
inline " {"
inline "  if(length>=arity)"
inline "   return"
inline " }"
inline ""
inline " const message=\"Expecting \"+arity+\" argument(s) (\"+length+\" given)\""
inline ""
inline " throw new Error(message)"
inline "}"
