fn unaccent x:str
 let r replace x "à" "a"
 let r replace r "â" "a"
 let r replace r "ä" "a"
 let r replace r "æ" "ae"
 let r replace r "ç" "c"
 let r replace r "é" "e"
 let r replace r "è" "e"
 let r replace r "ê" "e"
 let r replace r "ë" "e"
 let r replace r "î" "i"
 let r replace r "ï" "i"
 let r replace r "ô" "o"
 let r replace r "ö" "o"
 let r replace r "œ" "oe"
 let r replace r "ù" "u"
 let r replace r "û" "u"
 let r replace r "ü" "u"
 let r replace r "ÿ" "y"
 let r replace r "À" "A"
 let r replace r "Â" "A"
 let r replace r "Ä" "A"
 let r replace r "Æ" "AE"
 let r replace r "Ç" "C"
 let r replace r "É" "E"
 let r replace r "È" "E"
 let r replace r "Ê" "E"
 let r replace r "Ë" "E"
 let r replace r "Î" "I"
 let r replace r "Ï" "I"
 let r replace r "Ô" "O"
 let r replace r "Ö" "O"
 let r replace r "Œ" "OE"
 let r replace r "Ù" "U"
 let r replace r "Û" "U"
 let r replace r "Ü" "U"
 let r replace r "Ÿ" "Y"

 ret r
end
